
---
services:
  nginx:
    image: nginx:stable-alpine  
# Uses the stable Alpine-based NGINX release
    container_name: piwigo-nginx
    ports:
      - "1080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - piwigo

---
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:16.4.0
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/atif/piwigo/config/:/config
      - /home/atif/piwigo/gallery:/gallery
    expose:
      - "80"

    restart: unless-stopped

---
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.8
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=pass

    volumes:
      - /home/atif/piwigo/mariadb-config:/config
    ports:
      - 3306:3306
restart: unless-stopped

---
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    
